sudo: required
dist: trusty

env:
  - BLLIPINTERFACE=cmd
  - BLLIPINTERFACE=python

language: cpp
compiler: gcc
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y libboost-dev liblbfgs-dev swig flex python-nose
  - sudo pip install python-coveralls
  - sudo pip install tox
  - sudo pip install flake8
before_script:
  - swig -version
script:
  - bash -c "[ $BLLIPINTERFACE == "cmd" ] && make world"
  - bash -c "[ $BLLIPINTERFACE == "python" ] && tox"
after_success:
  - coveralls
