language: cpp
compiler: gcc
before_install: sudo apt-get update
install: sudo apt-get install libboost-dev liblbfgs-dev
script:
  - make
  - make reranker
  - make -C second-stage/programs/features parallel-tools
