sudo: required
dist: trusty

language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository --yes ppa:ktm5j/uva-cs-ppa
  - sudo apt-get update
install:
  - sudo apt-get install libboost-dev liblbfgs-dev swig flex python-nose
  - sudo pip install python-coveralls
  - sudo pip install tox
before_script:
  - swig -version
script:
  - make
  - make reranker
  - make -C first-stage/PARSE all
  - make -C second-stage/programs/features parallel-tools
  - make sparseval
  - tox
after_success:
  - coveralls
